#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-JSON-RPC
Version  : 1.06
Release  : 1
URL      : https://cpan.metacpan.org/authors/id/D/DM/DMAKI/JSON-RPC-1.06.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/D/DM/DMAKI/JSON-RPC-1.06.tar.gz
Source1  : http://http.debian.net/debian/pool/main/libj/libjson-rpc-perl/libjson-rpc-perl_1.06-2.debian.tar.xz
Summary  : 'JSON RPC 2.0 Server Implementation'
Group    : Development/Tools
License  : Artistic-1.0 Artistic-1.0-Perl GPL-1.0
Requires: perl-JSON-RPC-license
Requires: perl-JSON-RPC-man
Requires: perl(Module::Build)
BuildRequires : perl(Module::Build)

%description
# NAME
JSON::RPC - JSON RPC 2.0 Server Implementation
# SYNOPSIS
# app.psgi
use strict;
use JSON::RPC::Dispatch;

%package license
Summary: license components for the perl-JSON-RPC package.
Group: Default

%description license
license components for the perl-JSON-RPC package.


%package man
Summary: man components for the perl-JSON-RPC package.
Group: Default

%description man
man components for the perl-JSON-RPC package.


%prep
tar -xf %{SOURCE1}
cd ..
%setup -q -n JSON-RPC-1.06
mkdir -p %{_topdir}/BUILD/JSON-RPC-1.06/deblicense/
mv %{_topdir}/BUILD/debian/* %{_topdir}/BUILD/JSON-RPC-1.06/deblicense/

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/perl-JSON-RPC
cp LICENSE %{buildroot}/usr/share/doc/perl-JSON-RPC/LICENSE
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot}
else
./Build install --installdirs=site --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.26.1/JSON/RPC.pm
/usr/lib/perl5/site_perl/5.26.1/JSON/RPC/Constants.pm
/usr/lib/perl5/site_perl/5.26.1/JSON/RPC/Dispatch.pm
/usr/lib/perl5/site_perl/5.26.1/JSON/RPC/Legacy.pm
/usr/lib/perl5/site_perl/5.26.1/JSON/RPC/Legacy/Client.pm
/usr/lib/perl5/site_perl/5.26.1/JSON/RPC/Legacy/Procedure.pm
/usr/lib/perl5/site_perl/5.26.1/JSON/RPC/Legacy/Server.pm
/usr/lib/perl5/site_perl/5.26.1/JSON/RPC/Legacy/Server/Apache2.pm
/usr/lib/perl5/site_perl/5.26.1/JSON/RPC/Legacy/Server/CGI.pm
/usr/lib/perl5/site_perl/5.26.1/JSON/RPC/Legacy/Server/Daemon.pm
/usr/lib/perl5/site_perl/5.26.1/JSON/RPC/Parser.pm
/usr/lib/perl5/site_perl/5.26.1/JSON/RPC/Procedure.pm
/usr/lib/perl5/site_perl/5.26.1/JSON/RPC/Test.pm

%files license
%defattr(-,root,root,-)
/usr/share/doc/perl-JSON-RPC/LICENSE

%files man
%defattr(-,root,root,-)
/usr/share/man/man3/JSON::RPC.3
/usr/share/man/man3/JSON::RPC::Constants.3
/usr/share/man/man3/JSON::RPC::Dispatch.3
/usr/share/man/man3/JSON::RPC::Legacy.3
/usr/share/man/man3/JSON::RPC::Legacy::Client.3
/usr/share/man/man3/JSON::RPC::Legacy::Procedure.3
/usr/share/man/man3/JSON::RPC::Legacy::Server.3
/usr/share/man/man3/JSON::RPC::Legacy::Server::Apache2.3
/usr/share/man/man3/JSON::RPC::Legacy::Server::CGI.3
/usr/share/man/man3/JSON::RPC::Legacy::Server::Daemon.3
/usr/share/man/man3/JSON::RPC::Parser.3
/usr/share/man/man3/JSON::RPC::Procedure.3
/usr/share/man/man3/JSON::RPC::Test.3
